spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_catalog
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          batch_size: 100
        order_inserts: true
